[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bull_and_cow_anchor = "HHRf5RHpg1xi69rYjh6cdVeUTPYkdZxZGKGhhU2gBrSW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://testnet.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
